FALLBACK_ERROR_FORMAT: json
FORWARDED_FOR_HEADER: X-Forwarded-For
FORWARDED_SECRET:
GRACEFUL_SHUTDOWN_TIMEOUT: 15.0
KEEP_ALIVE: true
KEEP_ALIVE_TIMEOUT: 15
REQUEST_BUFFER_QUEUE_SIZE: 100
REQUEST_MAX_SIZE: 100000000
REQUEST_TIMEOUT: 60
RESPONSE_TIMEOUT: 60

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "qyGHtJBZUW"
  database: "sanic"
  max_connections: 17
  timeout: 5
mongo:
  host: "127.0.0.1"
  port: 27017
  serverSelectionTimeoutMS: 5000
redis:
  address: 'redis://127.0.0.1'
  db: 3
  encoding: "utf-8"
